# Modified from BasicSR (https://github.com/xinntao/BasicSR)

name: pi2rnet
model_type: Image_Restoration_Physics_Model
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  train: 
    name: divpano-train
    type: ImagewithPIDataset
    dataroot_gt: ./datasets/DIVPano_lmdb/DIVPano_Train_HR.lmdb
    dataroot_lq: ./datasets/DIVPano_lmdb/DIVPano_Train_LR.lmdb
    dataroot_psf: ./datasets/PI_Train.pth

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: divpano-val
    type: ImagewithPIDataset
    dataroot_gt: ./datasets/DIVPano_lmdb/DIVPano_Val_HR.lmdb
    dataroot_lq: ./datasets/DIVPano_lmdb/DIVPano_Val_LR.lmdb
    dataroot_psf: ./datasets/PI_Val.pth
    io_backend:
      type: lmdb

# network structures
network_g:
  type: PI2RNet
  wf: 64
  hin_position_left: 0
  hin_position_right: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
#  visualization: visual/ntire2021-demo

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 140000
    eta_min: !!float 1e-7

  total_iter: 140000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: FuseLoss
    loss_weight: 0.5
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false
  grids: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
